---

name_project: sap-vagrant
environment: dev

vagrant:
  limit: ''
  verbose: 'vvvv'
  sudo: true

servers:
  - name: 1.web.sap-vagrant.vm
    ip: 10.10.10.20
    box: ubuntu/xenial64
    hostname: 1-web-sap-vagrant.vm
    ram: 6144
